### ISSUE TITLE
Logging is too cluttered

### ISSUE THREAD

**Issue by Zokalyx** [Zokalyx/theconfluence#3]
Seems like Heroku already provides some of the same logging format as the one that's in the code
![image](https://user-images.githubusercontent.com/36007346/151671012-8fae43ce-f4f8-4277-bcc6-86fffe4c9587.png)

_Originally posted by @Zokalyx in https://github.com/Zokalyx/theconfluence/pull/1#discussion_r795077571_

**Comment by Thejusko** [comment]
You can change the output log level in the logging config at the start of the file.
WARN as example will only output LOGGER.warn and LOGGER.error

Which data does Heroku provides? ( The Screenshot doesn't contain anything )

**Comment by Zokalyx** [comment]
I still want to see info level log, but I want each print to fit in its own line.

Yeah my bad, I automatically assumed that all of the black text was part of the logging, but apparently not. I was talking about `2022-0129T17:26:53.583408+00:00 app[worker.1]`. [It doesn't look like this can be modified :(](https://devcenter.heroku.com/articles/logging#log-format)

**Comment by Zokalyx** [comment]
As a "temporary" measure, I will remove the timestamps from the new logger. I won't change this repo, just the Heroku one. (Maybe I should sync the changes?)

EDIT: I'm also modifying the lengths of each "part" of the logging format and adding a newline right before the content of the log.
New logs look like this:

![image](https://user-images.githubusercontent.com/36007346/151680690-5daad1d0-252d-4925-bc01-4bd91504699b.png)
